### DISCUSSION TITLE
Trying your cakephp4 image

### DISCUSSION THREAD

**Discussion by viniciusbig** [shinsenter/php#13] [General]
The concept behind this image and how well-suited it is for production really appeal to me!
Fantastic work!

However, I have a question regarding the cakephp4 image.
(I was unable to look for an answer because I couldn't locate the source code for it.)

I'm mounting my image with a directory as the document root path using docker-composer.

The image is downloading the most recent CakePHP version and overwriting everything even though this folder is *not empty*.

Here is the docker-composer snippet

```yaml
cakephp4:
    image: shinsenter/cakephp4:latest
    env_file: .env
    volumes:
      - ./src:/var/www/html
      - ./ssl-certs:/etc/ssl/web
    environment:
      TZ: UTC
      PUID: ${UID:-9999}
      PGID: ${GID:-9999}
    ports:
      - "${APACHE_PORT}:80"
      - "${APACHE_PORT_HTTPS}:443"
    links:
      - mysql
      - redis
```

`src` contains a index.php file with phpinfo() inside.

Can you help me understand that?
Thanks!
