### DISCUSSION TITLE
Is possible do not gen index.php file default?

### DISCUSSION THREAD

**Discussion by huthief** [shinsenter/php#26] [Ideas]
If the WEBHOME not exists index.php file, docker always gen one. 
It always make the defaule index.html not work.
Is possible cancel it ?
I tird rm in customer Dockerfile , but it is not work.
Thank yoiu.

**Comment by shinsenter** [comment]
Hey @huthief !

Thank you for the feedback!
I will fix the installation scripts and get back to you later.

Best regards.

**Comment by shinsenter** [comment]
@huthief 

With the latest version, you can now set the container to not create index.php on startup by overriding the AUTO_CREATE_INDEX_FILE to `false` (the value is `false` by default).

Dockerfile example:

```Dockerfile
ENV AUTO_CREATE_INDEX_FILE=false
```

docker-compose.yml example:
```yml
version: '3'
services:
  my-app:
    image: shinsenter/phpfpm-nginx:latest
    volumes:
      - ./my-website:/var/www/html
    environment:
      AUTO_CREATE_INDEX_FILE: false
```
