### DISCUSSION TITLE
Adding a database ot symfony image

### DISCUSSION THREAD

**Discussion by rccc** [shinsenter/php#63] [General]
Hello,

I am seeing this : https://github.com/shinsenter/php/tree/5.x/src/webapps/symfony and if you have some doc on how to add a dabase (postgres or mariadb for exemple) and how to set the database_url in this case.

Many thanks in advance !

**Comment by shinsenter** [comment]
@rccc 

I'm not sure exactly how you want to add documents. I also can't create or update examples for any specific project because each person will want to use different databases, possibly a remote DB rather than Docker.

In case you want to use a PostgreSQL database as a Docker container, you can create a simple `docker-compose.yml` file like this and run `docker compose up -d` to start the containers. However, you will need to declare additional configurations for Symfony to be able to interact with your database.

```yml
version: '3'
services:
  my_database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  my_symfony:
    image: shinsenter/symfony:latest
    restart: always
    volumes:
      - ./www:/var/www/html
      # - ./my_site.crt:/etc/ssl/site/server.crt
      # - ./my_site.key:/etc/ssl/site/server.key
    environment:
      DATABASE_URL: "postgresql://my_database:5432/db?serverVersion=16&charset=utf8"
    ports: 
      - 80:80
      - 443:443
      - 443:443/udp
```

The Symfony configuration sets the `DATABASE_URL` parameter to `postgresql://my_database:5432/db?serverVersion=16&charset=utf8`, which tells Symfony how to connect to the PostgreSQL database.

You will need to change the password environment variable to a strong password.
You can also change the `POSTGRES_USER`, `POSTGRES_PASSWORD` and `POSTGRES_DB` environment variables if you want to use a different username, password or database name.

You can find more information about configuring Symfony with PostgreSQL here:
- https://symfony.com/doc/current/the-fast-track/en/8-doctrine.html#changing-the-default-database-url-value-in-env
- https://hub.docker.com/_/postgres

I hope this helps!
