### ISSUE TITLE
[Bug]: Crater container is not accessible, Symfony Exception

### ISSUE THREAD

**Issue by UntouchedWagons** [shinsenter/php#18]
## Issue description
Crater container is not usable due to a Symfony exception. This occurs 100% of the time

## Environment

- Operating System Version: Ubuntu server 22.04
- Docker Version: 20.10.22

## Steps to reproduce the issue

1. `docker compose up -d`
2. Wait a bit for containers to start
3. Go to http://192.168.0.70:3080

## What is expected?
An installation guide most likely, I don't know what to expect really.

## Additional details / screenshots

`docker-compose.yaml`

```
version: "3.5"

networks:
  default:
  npm_default:
    external: true

services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: crater_mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - MYSQL_ROOT_PASSWORD=RelieveFutureEarly
      - MYSQL_DATABASE=crater
      - MYSQL_USER=crater
      - MYSQL_PASSWORD=DespoticLudicrousWorkerUnrestrained
    volumes:
      - ./appdata/mariadb:/config
    restart: unless-stopped

  redis:
    restart: unless-stopped
    container_name: crater_redis
    image: redis:latest

  crater:
    image: shinsenter/crater:latest
    restart: unless-stopped
    container_name: crater
    ports:
      - '3080:80'
    volumes:
      - ./appdata/crater:/var/www/html
    environment:
      - TZ=America/Toronto
      - PUID=1000
      - PGID=1000
      - REDIS_HOST=redis
      - DB_HOST=mariadb
      - DB_DATABASE=crater
      - DB_USERNAME=crater
      - DB_PASSWORD=DespoticLudicrousWorkerUnrestrained
      # - CRATER_QUEUE_ENABLED=true
      # - CRATER_QUEUE_OPTIONS=--timeout=60 --tries=3 redis
      # - CRATER_SCHEDULE_ENABLED=true
    links:
      - mariadb
      - redis
```
The symfony exception

![canvas](https://user-images.githubusercontent.com/160996/209702665-c21da8c5-a5f6-416d-8c69-027e0820edf0.png)
