### ISSUE TITLE
Running the container as non-root

### ISSUE THREAD

**Issue by melwinek** [shinsenter/php#198]
The container only runs as root.
Is there a solution for this?

```
franken  | !!! Please run this container as the root user !!!
franken exited with code 0
```

**Comment by shinsenter** [comment]
@melwinek 

Hello, thanks for reaching out.

I believe this issue is being discussed in another topic on FrankenPHP. Please follow the progress there and hopefully, you'll find the information you need.
https://github.com/dunglas/frankenphp/issues/607

I'll close this issue as it's not directly related to PHP features.

**Comment by melwinek** [comment]
This is not necessarily a FrankenPHP problem.
Below I am pasting my Dockerfile and dockercompose.yaml which run correctly as e.g. user 1000.

```
FROM dunglas/frankenphp:latest-alpine
RUN install-php-extensions \
        pdo_mysql \
        gd \
        intl \
        zip \
        opcache
```

```
services:
  franken:
    build:
      context: .
    container_name: franken
    restart: unless-stopped
    user: 1000:1000
    ports:
      - "80:80"
      - "443:443"
      - "8386:8386"
      - "443:443/udp"
```
