### ISSUE TITLE
PHP-FPM Configuration in Docker Compose  '/usr/local/etc/php-fpm.d/zz-generated-settings.conf': No such file or directory (2)

### ISSUE THREAD

**Issue by hhaswan** [shinsenter/php#199]
I have configured the `docker-compose.yml` (using `shinsenter/php:7.1-fpm-nginx`) with the following environment variables:

```
environment:
  - TZ=Asia/Makassar
  - DOCUMENT_ROOT=/app
  - ALLOW_RUNTIME_PHP_ENVVARS=1
  - PHP_MAX_EXECUTION_TIME=1800
  - PHP_POST_MAX_SIZE=100M
  - PHP_UPLOAD_MAX_FILESIZE=100M
  - PHP_MAX_INPUT_TIME=600
  - PHP_MAX_INPUT_VARS=3000
  - PHP_REQUEST_TERMINATE_TIMEOUT=1800
```
However, when running `docker compose logs -f`, I encounter the following error:
```
app-3  | [12-Mar-2025 00:30:08] ERROR: failed to open configuration file '/usr/local/etc/php-fpm.d/zz-generated-settings.conf': No such file or directory (2)
app-3  | [12-Mar-2025 00:30:13] ERROR: failed to load configuration file '/usr/local/etc/php-fpm.d/zz-generated-settings.conf'
```
This error occurs after adding `PHP_REQUEST_TERMINATE_TIMEOUT=1800`. I would like to adjust PHP-FPM for the `request_terminate_timeout` variable. Any assistance would be appreciated.

**Comment by shinsenter** [comment]
Hi @hhaswan 

I’ve reviewed your setup and tried using the following docker-compose.yml to create a container, and I didn’t notice anything unusual.

```yml
services:
  test:
    image: shinsenter/php:7.1-fpm-nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Makassar
      - DOCUMENT_ROOT=/app
      - ALLOW_RUNTIME_PHP_ENVVARS=1
      - PHP_MAX_EXECUTION_TIME=1800
      - PHP_POST_MAX_SIZE=100M
      - PHP_UPLOAD_MAX_FILESIZE=100M
      - PHP_MAX_INPUT_TIME=600
      - PHP_MAX_INPUT_VARS=3000
      - PHP_REQUEST_TERMINATE_TIMEOUT=1800

```

Could you provide any additional information that you think might be relevant?
