### ISSUE TITLE
PHP variable $_SERVER['SCRIPT_FILENAME'] starts with double slash.

### ISSUE THREAD

**Issue by JAGulin** [shinsenter/php#209]
This might be a misunderstanding rather than a bug, so any input is helpful. 

I have an apache behind a reverse-proxy, serving http.
The issue noted is that the PHP variable $_SERVER['SCRIPT_FILENAME'] starts with double slash. It's not a problem for normal operation, but certain scripts uses this variable with unexpected results. 

To exclude any .htaccess configuration and avoiding the reverse proxy, I've tested this locally with a new docker setup.

This is the entry under `service:` in /root/docker-compose.yml

```
  web-test:
     image: shinsenter/phpfpm-apache:latest
     container_name: webtest
     restart: always
     ports:
       - 127.0.0.1:19000:80 # localhost access
     environment:
       - APP_PATH=/home/web-test
       - DOCUMENT_ROOT=/test
     volumes:
       - /srv/web-test:/var/www/html  # default dir
       - /srv/web-test:/home/web-test # match the old dir
```

With this test setup
```
sudo mkdir -p /srv/web-test/test/sub
cat /srv/web-test/test/sub/test.php
<?php
echo "<PRE>";
print_r($_REQUEST);
$S = $_SERVER;
$S["PHP_AUTH_PW"] = "***";
print_r($S);
echo "</PRE>";

echo 'PHP version: ' . phpversion();
?>

sudo /usr/bin/docker compose -f /root/docker-compose.yml up -d --force-recreate web-test

curl localhost:19000/sub/test.php |& grep -E "html|test"
    [DOCUMENT_ROOT] => /home/web-test/test
    [PWD] => /home/web-test
    [APP_PATH] => /home/web-test
    [PATH] => /command:/home/web-test/vendor/bin:/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    [SCRIPT_NAME] => /sub/test.php
    [REQUEST_URI] => /sub/test.php
    [SCRIPT_FILENAME] => //home/web-test/test/sub/test.php
    [CONTEXT_DOCUMENT_ROOT] => /home/web-test/test
    [PHP_SELF] => /sub/test.php
```
Note that SCRIPT_FILENAME starts with // rather than /, while both DOCUMENT_ROOT and APP_PATH are ok and SCRIPT_NAME is relative to ROOT as expected.

I tried `APP_PATH=home/web-test` but probably didn't figure out where to put the files, because I only got 403 Forbidden. 

I also removed the `environment:` from docker-compose to ensure that the problem remains with the defaults:

```
curl localhost:19000/test/sub/test.php |& grep -E "html|test"

    [PWD] => /var/www/html
    [APP_PATH] => /var/www/html
    [PATH] => /command:/var/www/html/vendor/bin:/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    [SCRIPT_NAME] => /test/sub/test.php
    [REQUEST_URI] => /test/sub/test.php
    [SCRIPT_FILENAME] => //var/www/html/test/sub/test.php
    [CONTEXT_DOCUMENT_ROOT] => /var/www/html
    [DOCUMENT_ROOT] => /var/www/html
    [PHP_SELF] => /test/sub/test.php
```
