### ISSUE TITLE
[Bug]: Crater Example docker-compose.yml not working

### ISSUE THREAD

**Issue by natterstefan** [shinsenter/php#21]
## Issue description

I get multiple errors when starting the docker image with the given example compose file.

## Environment

- Opertaing System Version: macos
- Docker Version: 20.10.21

## Steps to reproduce the issue

1. Take my `docker-compose.yml` and start it with `docker-compose up`. Attention: I used different ports for crater and myql, and the network part is taken from [crater's docker-compose example](https://github.com/crater-invoice/crater/blob/393fe20010d4ddbc4eb49e739000f55d8d7e0b8b/docker-compose.yml#L17-L18).

```yml
version: '3'

services:
  crater:
    # do not update until https://github.com/shinsenter/php/issues/18#issuecomment-1366262015 is fixed
    image: shinsenter/crater:php8.1
    restart: always
    volumes:
      - ./volumes/crater:/var/www/html:rw
      # - ./ssl-certs:/etc/ssl/web
    environment:
      TZ: Europe/Vienna
      PUID: ${UID:-9999}
      PGID: ${GID:-9999}
      # REDIS_HOST: redis
      DB_HOST: mysql
      DB_DATABASE: crater
      DB_USERNAME: root
      DB_PASSWORD: mydb_p@ssw0rd
      # CRATER_QUEUE_ENABLED: true
      # CRATER_QUEUE_OPTIONS: --timeout=60 --tries=3 redis
      # CRATER_SCHEDULE_ENABLED: true
    ports:
      - "3050:80"
      # - "443:443"
    links:
      - mysql
      # - redis
    networks:
      - crater

  mysql:
    image: mysql:8.0.32
    restart: always
    environment:
      TZ: Europe/Vienna
      MYSQL_ROOT_PASSWORD: mydb_p@ssw0rd
      MYSQL_DATABASE: crater
    volumes:
      - "./volumes/mysql/data:/var/lib/mysql"
      # - "./volumes/mysql/dump:/docker-entrypoint-initdb.d"
    ports:
      - "3060:3306"
    networks:
      - crater

  # redis:
  #   image: redis:7.0.8-alpine
  #   ports:
  #     - "6379:6379"

networks:
  crater:
    driver: bridge
```

## What is expected?

- Setup and Installation works (e.g. database connection info is taken from ENV variables)

## Additional details / screenshots

- Related issues: https://github.com/shinsenter/php/issues/11

### Screenshots

Not sure why this is happening at the moment
<img width="1565" alt="image" src="https://user-images.githubusercontent.com/1043668/213100913-c5a12cf8-610d-4352-8c11-95a38d950be6.png">

Values are not taken from the compose file as expected
<img width="1563" alt="image" src="https://user-images.githubusercontent.com/1043668/213100960-e203b162-a387-4aaf-85bd-da335c78e1c0.png">

The port is not taken from the compose file, which leads to an error as expected
<img width="1658" alt="image" src="https://user-images.githubusercontent.com/1043668/213101033-d2a7ce85-2f66-4ba5-b2b2-c059dd9f0316.png">

Even when I change the port to the one in the compose file it does not work:

<img width="1641" alt="image" src="https://user-images.githubusercontent.com/1043668/213101151-527909a5-2504-4c90-bd7a-e4231e746510.png">
