### ISSUE TITLE
How to create multiple sites in one container?

### ISSUE THREAD

**Issue by kadifu** [shinsenter/php#66]
I want to create 3 sites in a container: a.test.com, b.test.com, c.test.com.
How to generate a container using the image php-fpm-apache?

**Comment by shinsenter** [comment]
Hi @kadifu 

It seems that your question isn't related to my Docker images but rather a common query about Apache server configurations.

You can definitely customize the Apache config to run three different websites on the same container. There are many articles on this topic available online, and I recommend searching for the most suitable method for your needs.

Btw, I encourage you to run each website on a separate container because each website requires its own environment. You can use Traefik to route requests to each container you want without having to modify the Apache configuration. Learn more here: https://doc.traefik.io/traefik/providers/docker/

Best regards

**Comment by kadifu** [comment]
@shinsenter 
Thanks, I got it.
Another question, I used the following script to install xdebug, but I didn't see the xdebug module in phpinfo(). Is there anything else I need to do?

```
FROM shinsenter/php:7.3-fpm-apache
RUN phpaddmod xdebug
```

**Comment by shinsenter** [comment]
@kadifu 

```dockerfile
FROM shinsenter/php:7.3-fpm-apache
RUN phpaddmod xdebug
```

Did you start your container from the Docker image you built with the above Dockerfile, or is your running container using my `shinsenter/php:7.3-fpm-apache` image (which doesn't have the `xdebug` module)?

To check if the `xdebug` module is present, run the following command inside the container:

```shell
php -m
```

For example, expected result may be look like this:
```
[PHP Modules]
<...>
xdebug
<...>

[Zend Modules]
Xdebug
Zend OPcache
```

**Comment by kadifu** [comment]
@shinsenter 
Dockerfile contents：
```
FROM shinsenter/php:7.3-fpm-apache
RUN phpaddmod xdebug
```

docker-compose.yml contents:
```
services:
  website:
    build:
        dockerfile: Dockerfile
    container_name: login.appeon.com
    volumes:
        - /home/apache/htdocs/www-sub-sites:/var/www/html
    ports:
       - "8081:80"
    environment:
      APP_PATH: "/var/www/html/login.appeon.com"
      PHP_DISPLAY_ERRORS: "1"
      PHP_POST_MAX_SIZE: "20M"
      PHP_UPLOAD_MAX_FILESIZE: "20M"
      PHP_SESSION_COOKIE_HTTPONLY: "1"
      PHP_MAX_EXECUTION_TIME: "200"
      PHP_PM: "dynamic"
      PHP_PM_MAX_CHILDREN: "100"
      PHP_PM_START_SERVERS: "16"
      PHP_PM_MIN_SPARE_SERVERS: "8"
      PHP_PM_MAX_SPARE_SERVERS: "24"
      PHP_PM_MAX_REQUESTS: "1000"
      TZ: "America/New_York"
    restart: always
```
Container startup script：
`docker compose  -f ./docker-compose.yml -p login-appeon-com up -d --force-recreate --remove-orphans`

And run the php -m command inside the container，expected result 
```
root@8da1bfb630b3:/var/www/html/login.appeon.com# php -m
[PHP Modules]
apcu
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
intl
json
libxml
mbstring
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
```
